---
title: "Indicadores - PFGP"
# subtitle: "Análise da representatividade (2016-2026)"
author: "CGINF/DIGID/SGP/MGI"
output:
  html_document:
    theme: default
    # css: css_gabriel.css
    self-contained: false
    toc: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE, echo=FALSE}
library(readxl)
library(ggplot2)
library(plotly)
library(knitr)
library(kableExtra)
library(magrittr)
library(DT)
library(janitor)
library(dplyr)
library(tidyverse)
library(crosstalk)
library(tidyr)
library(htmltools)
library(stringi)

source('data-raw/metodos.r')
```

```{r, echo=FALSE, include=FALSE}
#leitura da base de dados
pfgp_indicadores <- read_excel("data-raw/data_pfgp/plataforma_pfgp_indicadores 2.xlsx",sheet="Indicadores PFGP") %>%
  janitor::clean_names()

```


## Introdução

A princípio, havia **`r NROW(pfgp_indicadores)`** indicadores sugeridos por `r pfgp_indicadores$embasamento_sugestao %>% na.omit() %>%lista_e(" e ")`

```{r, echo=FALSE, warning=F, message=F}


limpar_texto <- function(x) {
  
  x %>%
    iconv(from = "", to = "UTF-8", sub = "") %>%
    
    # transforma quebras de linha em espaço
    stri_replace_all_regex("[\\r\\n]+", " ") %>%
    
    # remove outros caracteres invisíveis
    stri_replace_all_regex("[\\p{Cc}\\p{Cf}]", "") %>%
    
    # remove sequências tipo \u0080
    stri_replace_all_regex("\\\\u[0-9a-fA-F]{4}", "") %>%
    
    # junta espaços duplicados
    stri_replace_all_regex("\\s+", " ") %>%
    
    trimws()
}

pfgp_indicadores <- pfgp_indicadores %>%
  mutate(
    across(
      where(is.character),
      limpar_texto
    )
  ) %>% filter(grepl("sim",apresentacao_pfgp_2030_02_06,ignore.case = T),
               status != "Excluído")

pfgp_indicadores$dim4 <- as.numeric(pfgp_indicadores$dim4)
```


No ENGP 2026, foram apresentados **`r NROW(pfgp_indicadores)`**.


## Dimensões

```{r, echo=FALSE}

# tabela de tradução dos nomes
nomes_dim <- c(
  "dim1" = "1. Planejamento, Diagnóstico da Força de Trabalho e Processo Seletivo​",
  "dim2" = "2. Carreiras, Cargos, Progressão e Promoção​",
  "dim3" = "3. Alocação, Ambientação, Estágio Probatório e Bem-Estar​",
  "dim4" = "4. Desenvolvimento e Desempenho de Pessoas e Formação de Lideranças Públicas​",
  "dim5" = "5. Remuneração, Benefícios, Reconhecimento e Recompensas Não Pecuniárias",
  "dim6" = "6. Aposentação, Pensões e Desligamentos"
)

grafico_flags_interativo <- function(dados, titulo){
  
  dados_long <- dados %>%
    pivot_longer(
      cols = starts_with("dim"), 
      names_to = "Categoria", 
      values_to = "Marcacao"
    ) %>%
    filter(!is.na(Marcacao) & Marcacao == 1) %>%
    group_by(Categoria) %>%
    summarise(Qtd = n(), .groups = "drop") %>%
    arrange(desc(Qtd))
  
  

  
  
  dados_long <- dados_long %>%
    mutate(
      Categoria_Nome = recode(
        Categoria,
        !!!nomes_dim
      )
    )
  
  
  dados_long$Categoria_Nome <- factor(
    dados_long$Categoria_Nome,
    levels = dados_long$Categoria_Nome
  )
  
  
  plot_ly(
    dados_long,
    x = ~Categoria_Nome,
    y = ~Qtd,
    type = 'bar',
    marker = list(
      color = '#0000aa',
      line = list(color = '#0000aa', width = 1)
    ),
    text = ~paste(
      "Dimensão", Categoria_Nome,
      "<br>Quantidade:", Qtd
    ),
    hoverinfo = 'text'
  ) %>%
    layout(
      title = titulo,
      xaxis = list(
        title = "Dimensões",
        showticklabels = FALSE
      ),
      yaxis = list(
        title = "Total de IDs",
        showgrid = TRUE
      ),
      margin = list(b = 100)
    )
}

grafico_flags_interativo(pfgp_indicadores, "Total de IDs por Dimensão")

```



## Status
```{r, echo=FALSE}
#total de indicadores com status "dados obtidos/a calcular"
#ajeitar a categoria dados obtidos está com carcateres diferentes

tabela_status <- table(pfgp_indicadores$status) %>%
  as.data.frame() %>%
  rename(status = Var1, Frequencia = Freq) %>% # Rename é mais limpo que colnames
  mutate(Porcentagem = (Frequencia / sum(Frequencia)) * 100,
         Porcentagem = round(Porcentagem, 1)) # Arredonda para 1 casa decimal

# 2. Exibir a tabela
tabela_status %>%
  mutate(Porcentagem = paste0(Porcentagem, "%")) %>% # Formata com símbolo de %
  kable(col.names = c("Status", "Frequencia", "%"), 
        align = "clc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = FALSE, 
                position = "center")

#criar outras tabelas usando botões que se atualizem quanto ao nível de dificuldade
```


```{r, echo=FALSE}
tabela_status_dim <- pfgp_indicadores %>%
  pivot_longer(
    cols = starts_with("dim"),
    names_to = "Dimensao",
    values_to = "Flag"
  ) %>% 
  filter(Flag == 1) %>% 
  group_by(Dimensao, status) %>%
  summarise(
    Qtd = n_distinct(id_indicador),
    .groups = "drop"
  ) %>% 
  group_by(Dimensao) %>%
  mutate(
    Total = sum(Qtd),
    Valor = paste0(Qtd, " (", round(Qtd/Total*100, 1), "%)")
  ) %>%
  ungroup() %>%
  select(Dimensao,Total, status, Valor) %>%
  pivot_wider(
    names_from = status,
    values_from = Valor,
    values_fill = "-",
    names_sort = TRUE
  ) %>% 
  mutate(Dimensao = nomes_dim[Dimensao])

tabela_status_dim %>%
  DT::datatable(rownames = F)
```


```{r, echo=FALSE}
# 1. Preparação dos Dados
dados_long <- pfgp_indicadores %>%
  mutate(ID = row_number()) %>%
  pivot_longer(
    cols = starts_with("dim"),
    names_to = "Categoria",
    values_to = "Marcacao"
  ) %>%
  filter(Marcacao == 1)

# 2. Criar objeto de dados compartilhados
shared_dados <- SharedData$new(dados_long, group = "dimensoes")


```




## Dimensão
```{r, echo=FALSE}
grafico_dimensao <- function(nome_dimensao, titulo_dimensao){
  
  # 1. Quebra o título visual
  titulo_visual <- paste(
    strwrap(titulo_dimensao, width = 35),
    collapse = "<br>"
  )
  
  # 2. Título do balão
  titulo_balao <- paste(
    strwrap(titulo_dimensao, width = 40),
    collapse = "<br>"
  )
  
  plot_ly(
    shared_dados,
    x = ~Categoria, 
    type = "histogram",
    
    marker = list(
      color = '#0000aa',
      line = list(
        color = '#0000aa',
        width = 1.5
      )
    ),
    
    hovertemplate = paste0(
      "<span style='font-size:12px;'><b>",
      titulo_balao,
      "</b></span>",
      "<br>Quantidade: <b>%{y}</b>",
      "<extra></extra>"
    ),
    
    transforms = list(
      list(
        type = "filter",
        target = ~Categoria,
        operation = "=",
        value = nome_dimensao
      )
    )
  ) %>%
    layout(
      annotations = list(
        text = titulo_visual,
        xref = "paper",
        yref = "paper",
        showarrow = FALSE,
        x = 0.5,
        y = 1.3,
        font = list(size = 11)
      ),
      margin = list(t = 100, b = 40, l = 40, r = 40),
      xaxis = list(showticklabels = FALSE, title = ""),
      yaxis = list(title = "Quantidade", automargin = TRUE)
    )
}
div(class = "row",
    div(class = "col-md-6", filter_select("fonte", "Fonte:", shared_dados, ~fonte)),
    div(class = "col-md-6", filter_select("dificuldade", "Dificuldade:", shared_dados, ~dificuldade_obtencao))
)
div(class = "row",
  div(class = "col-md-4",
      grafico_dimensao("dim1", "Dimensão 1: Planejamento, Diagnóstico da Força de Trabalho e Processo Seletivo​")
  ),
  div(class = "col-md-4",
      grafico_dimensao("dim2", "Dimensão 2: Carreiras, Cargos, Progressão e Promoção​")
  ),
  div(class = "col-md-4",
      grafico_dimensao("dim3", "Dimensão 3: Alocação, Ambientação, Estágio Probatório e Bem-Estar​")
  ),
   div(class = "col-md-4",
      grafico_dimensao("dim4", "Dimensão 4: Desenvolvimento e Desempenho de Pessoas e Formação de Lideranças Públicas​")
  ),
  div(class = "col-md-4",
      grafico_dimensao("dim5", "Dimensão 5: Remuneração, Benefícios, Reconhecimento e Recompensas Não Pecuniárias​")
  ),
    div(class = "col-md-4",
      grafico_dimensao("dim6", "Dimensão 6: Aposentação, Pensões e Desligamentos​")
  )
)
```



## Resumo dos indicadores {.tabset}

### Cadeia de Valores

```{r, echo=FALSE, warning=FALSE}
#qtd de indicadores por tipo de: cadeia de valores/marco lógico
tabela_resumo1 <- table(pfgp_indicadores$tipo_cadeia_valor,useNA = "always")
tabela_resumo2 <- table(pfgp_indicadores$tipo_marco_logico, useNA = "always")


# Converte o summary em uma tabela tratável
dados_tabela1 <- as.data.frame(tabela_resumo1)
dados_tabela2 <- as.data.frame(tabela_resumo2)

# Converte vars para fatores ordenados
dados_tabela1 <- mutate(dados_tabela1,Var1 = factor(Var1,
                                                     levels = c('Gestão de RH – Atividades e Processos',
                                                                'Gestão de RH – Resultados',
                                                                'Objetivos organizacionais'),
                                                     ordered = T
                                                     )
                        )%>%
  arrange(Var1)

dados_tabela2 <- mutate(dados_tabela2,Var1 = factor(Var1,
                                                     levels = c('Insumo',
                                                                'Atividade',
                                                                'Produto',
                                                                'Resultado',
                                                                'Impacto'),
                                                     ordered = T
                                                     )
                        )%>%
  arrange(Var1)

colnames(dados_tabela1) <- c("Cadeia de Valores", "Quantidade")
dados_tabela1$Quantidade <- as.numeric(as.character(dados_tabela1$Quantidade))
colnames(dados_tabela2) <- c("Marco Lógico", "Quantidade")


#Tabela para visualização
dados_tabela1 %>%
  mutate(
    Porcentagem = (Quantidade / sum(Quantidade)) * 100,
    # Arredonda para 1 casa decimal e adiciona o símbolo de %
    Porcentagem = paste0(round(Porcentagem, 1), "%")
  ) %>%
  kable(
    col.names = c("Cadeia de Valores", "Quantidade", 
                  "Porcentagem"),
    align = "cl",
    format = "html"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )


#Visualização com o gráfico de barras
grafico_indicadores <- function(dados, coluna_categoria, coluna_valor, titulo){
  
  # 1. Preparar os dados
  dados_plot <- dados %>%
    group_by(.data[[coluna_categoria]]) %>%
    summarise(valor_total = sum(.data[[coluna_valor]], na.rm = TRUE)) #%>%
    # arrange(desc(valor_total))
  
  # 2. Criar o gráfico
  plot_ly(
    dados_plot,
    x = ~reorder(.data[[coluna_categoria]], -valor_total),
    y = ~valor_total,
    type = 'bar',
    marker = list(color = '#0000aa', line = list(color = '#404040', width = 0.5)),
    # AQUI ESTÁ A MUDANÇA: deixamos apenas o valor no texto do hover
    text = ~paste0("Quantidade: ", valor_total),
    hoverinfo = 'x+text' # Mostra o nome do eixo X + o nosso texto personalizado
  ) %>%
    layout(
      title = list(text = titulo, font = list(size = 18, family = "Arial", weight = "bold")),
      xaxis = list(
        title = coluna_categoria,showticklabels = FALSE,
        categoryorder = "array",
        categoryarray = ~reorder(.data[[coluna_categoria]], -valor_total),
        showgrid = FALSE
      ),
      yaxis = list(
        title = "Quantidade",
        showgrid = TRUE,
        gridcolor = '#f0f0f0'
      ),
      plot_bgcolor = 'white',
      paper_bgcolor = 'white',
      margin = list(t = 60, b = 80)
    )
}

# Chamar a função
grafico_indicadores(
  dados_tabela1,
  "Cadeia de Valores",
  "Quantidade",
  "Total de Indicadores por Cadeia de Valores"
)
```



#### Tabela Resumo


```{r, echo=FALSE}
tabela_dimensoes <- pfgp_indicadores %>%
  
  pivot_longer(
    cols = starts_with("dim"),
    names_to = "Dimensao",
    values_to = "Flag"
  ) %>%
  
  filter(Flag == 1) %>%
  
  # transforma dim1 -> 1
  mutate(Dimensao = sub("^dim", "", Dimensao)) %>%
  
  group_by(Dimensao) %>%
  
  summarise(
    Quantidade = n_distinct(id_indicador),
    Cadeia1 = n_distinct(id_indicador[tipo_cadeia_valor == "Gestão de RH – Atividades e Processos"]),
    Cadeia2 = n_distinct(id_indicador[tipo_cadeia_valor == "Gestão de RH – Resultados"]),
    Cadeia3 = n_distinct(id_indicador[tipo_cadeia_valor == "Objetivos organizacionais"]),
    .groups = "drop"
  ) %>%
  
  mutate(
    `Gestão RH - Atividades e Processos` =
      paste0(Cadeia1, " (", round(Cadeia1/Quantidade*100,1), "%)"),
    
    `Gestão RH - Resultados` =
      paste0(Cadeia2, " (", round(Cadeia2/Quantidade*100,1), "%)"),
    
    `Objetivos Organizacionais` =
      paste0(Cadeia3, " (", round(Cadeia3/Quantidade*100,1), "%)")
  ) %>%
  
  select(
    Dimensao,
    Quantidade,
    `Gestão RH - Atividades e Processos`,
    `Gestão RH - Resultados`,
    `Objetivos Organizacionais`
  )

tabela_dimensoes %>%
  kable(
    col.names = c(
      "Dimensão",
      "Quantidade",
      "Gestão RH - Atividades e Processos (Qtd/%)",
      "Gestão RH - Resultados (Qtd/%)",
      "Objetivos Organizacionais (Qtd/%)"
    ),
    align = "ccccc"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )
```




### Marco Lógico
```{r, echo=FALSE, warning=FALSE}
dados_tabela2 %>%
  mutate(
    Porcentagem = (Quantidade / sum(Quantidade)) * 100,
    # Arredonda para 1 casa decimal e adiciona o símbolo de %
    Porcentagem = paste0(round(Porcentagem, 1), "%")
  ) %>%
  kable(
    col.names = c("Marco Lógico", "Quantidade", "Porcentagem"),
    align = "cl",
    format = "html"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = FALSE,
    position = "center"
  )

# Chamar a função
grafico_indicadores(
  dados_tabela2,
  "Marco Lógico",
  "Quantidade",
  "Total de Indicadores por Marco Lógico"
)



```


