project:
  buildId: ${Build.BuildId}
  name: ${PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}

deployment:
  applicationPort: ${APPLICATION_PORT}
  dockerImageName: ${DOCKER_IMAGE_NAME}
  dockerImageVersion: ${Build.BuildId}
  dockerRegistryProject: ${DOCKER_REGISTRY_PROJECT}
  dockerRegistryUrl: ${DOCKER_REGISTRY_URL}
  imagePullSecretsName: ${IMAGE_PULL_SECRETS_NAME}
  limitsCpu: ${LIMITS_CPU}
  limitsMem: ${LIMITS_MEM}
  maxUnavailable: ${MAX_UNAVAILABLE}
  maxSurge: ${MAX_SURGE}
  minReplicas: ${MIN_REPLICAS}
  requestsCpu: ${REQUESTS_CPU}
  requestsMem: ${REQUESTS_MEM}
  readinessPath: /
  livenessPath: /

service:
  port: ${APPLICATION_PORT}

ingress:
  certManagerClusterIssuer: ${CERT_MANAGER_CLUSTER_ISSUER}
  url: ${INGRESS_URL}

autoScalling:
  maxReplicas: ${MAX_REPLICAS}
  scallingByCpuPerc: ${SCALING_BY_CPU_PERC}
